name: allure-junit5-maven

on: [ push ]

jobs:
  runtest:
    name: generate-test-report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
             node-version: "16.15.0"
      - name: Publish
        run: |
            npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}    

      
